import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import CookieConsent from "react-cookie-consent";
import {CartProvider} from '@/context/context'
import CookieConsentBanner from '@/components/cookieBanner';
const inter = Inter({ subsets: ['latin'] })
import CookieFunctions from '@/components/cookieFunctions';
import Cart from '@/components/cart';
import NavBar from '@/components/navbar';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
        <NavBar/>
          <Cart/>
          {children}
          <CookieConsentBanner/>
        </CartProvider>
        
        </body>
    </html>
  )
}
