export const brands = [
    `almay`,
    `alva`,
    `anna sui`,
    `annabelle`,
    `benefit`,
    `boosh`,
    `burt's bees`,
    `butter london`,
    `cargo cosmetics`,
    `china glaze`,
    `clinique`,
    `colourpop`,
    `covergirl`,
    `dalish`,
    `deciem`,
    `dior`,
    `dr. hauschka`,
    `e.l.f.`,
    `essie`,
    `fenty`,
    `glossier`,
    `iman`,
    `l'oreal`,
    `marcelle`,
    `maybelline`,
    `milani`,
    `mineral fusion`,
    `misa`,
    `mistura`,
    `moov`,
    `nyx`,
    `orly`,
    `pacifica`,
    `physicians formula`,
    `piggy paint`,
    `pure anada`,
    `revlon`,
    `salon perfect`,
    `sante`,
    `sinful colours`,
    `smashbox`,
    `stila`,
    `suncoat`,
    `wet n wild`,
    `zorah`,
]

export const products = [
    `nail_polish`,
    `mascara`,
    `lipstick`,
    `lip_liner`,
    `foundation`,
    `eyeshadow`,
    `eyeliner`,
    `eyebrow`,
    `bronzer`,
    `blush`
]
export const tagList =[
`CertClean`,
`Chemical Free`,
`Dairy Free`,
`EWG Verified`,
`EcoCert`,
`Fair Trade`,
`Gluten Free`,
`Hypoallergenic`,
`Natural`,
`No Talc`,
`Non-GMO`,
`Organic`,
`Peanut Free Product`,
`Sugar Free`,
`USDA Organic`,
`Vegan`,
`alcohol free`,
`cruelty free`,
`oil free`,
`purpicks`,
`silicone free`,
`water free`,
]